#!/bin/bash
# usage: 
# stop_docker <容器1、容器2、容器3...> 停止容器1、容器2、容器3...
# stop_docker all 停止所有容器
if [ -z $1 ]
then
	echo "no argument provided! exit now..."
	exit 1
fi

if [ $1 == "all" ]
then
	sudo docker stop $(sudo docker ps -aq)
else
	for i in $@
	do
		sudo docker stop "$i"
	done
fi
# sudo docker stop $(sudo docker ps -aq)
